app:
  name: mathtest-core

jwt:
  header: Authorization
  expires_in: 3600 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: queenvictoria
spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/mathtests?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Windy610
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    cors:
      allowed-origins : "*"
      allowed-methods : GET, POST, PUT, OPTIONS, DELETE
      allowed-headers : Content-Type,Authorization,Origin,X-Requested-With,Accept,X-Frame-Options
      exposed-headers : Access-Control-Allow-Origin,Access-Control-Allow-Credentials
      max-age : 3600
      alllow-credentials : true
#management:
endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST, PUT, OPTIONS, DELETE
        allow-credentials: true
# HTTP to HTTPS
#server:
#  port: 8080
#  ssl:
#    key-aliasey: selfsigned
#    key-password: password
#    key-store: classpath:ttq.jks
#    key-store-provider: SUN
#    key-store-type: JKS
